@startuml


[*] --> DEVICE_OFF

state DEVICE_OFF
state SCANNING
state CHANNEL_LIST
state CLIENT_REGISTRATION
state AUTHORIZATION_INIT

SCANNING: + onEnter: getChannelList

CHANNEL_LIST: +onEnter: displayChannelList

CLIENT_REGISTRATION: + onEnter: requestClientInformation\nPOST /register \n{\n\tclient_name: 'Test client',\n\tsoftware_id: 'CPA AP Test',\n\tsoftware_version: '0.0.1'\n}

AUTHORIZATION_INIT: + onEnter: requestUserCode\nPOST /token\nclient_id=:cid&response_type=device_code
AUTHORIZATION_CHECK: + onEnter: requestAccessToken\nPOST /token\n{\n\tclient_id:cid\n\tgrant_type:'authorization_code'\n\tcode: 'device_code'\n}


AUTHORIZATION_PENDING: + onEnter: displayUserCode

state AUTHORIZATION_PENDING
state SUCCESSFUL_PAIRING
state ERROR

DEVICE_OFF -[#blue]-> DEVICE_ON: switch_on
DEVICE_ON --> SCANNING
SCANNING --> CHANNEL_LIST: onLoaded
SCANNING -right-> ERROR: No channel

CHANNEL_LIST -[#blue]-> CLIENT_REGISTRATION: onChannelClick [!isRegistered]
CHANNEL_LIST -[#blue]-> AUTHORIZATION_INIT: onChannelClick [isRegistered]

CLIENT_REGISTRATION --> AUTHORIZATION_INIT: onReply [201 Created]
CLIENT_REGISTRATION -[#gray]-> ERROR: onReply [*]

AUTHORIZATION_INIT --> AUTHORIZATION_PENDING: onReply [200]
AUTHORIZATION_INIT -[#gray]-> ERROR: onReply [*]


AUTHORIZATION_PENDING -[#blue]-> AUTHORIZATION_CHECK: onValidatePairingClick
AUTHORIZATION_CHECK --> SUCCESSFUL_PAIRING: onReply [200 OK, {token}]
AUTHORIZATION_CHECK --> AUTHORIZATION_PENDING: onReply [400, '{error:authorization_pending}']
AUTHORIZATION_CHECK -[#gray]-> ERROR: onReply [*]

SUCCESSFUL_PAIRING --> [*]

legend left

CPA Client

Note:
- Transition format: "trigger [guard] /effect"
- Blue arrows are user actions (ie click)
endlegend



' note right of STATE: "transition: trigger[guard]/effect"

@enduml
